//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyTask2Entities : DbContext
    {
        public MyTask2Entities()
            : base("name=MyTask2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ServiceArea> ServiceArea { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblSupplier> tblSupplier { get; set; }
    
        public virtual ObjectResult<sp_selectServiceArea_Result> sp_selectServiceArea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_selectServiceArea_Result>("sp_selectServiceArea");
        }
    }
}
