//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceArea
    {
        public int ServiceAreaId { get; set; }
        public string north { get; set; }
        public string south { get; set; }
        public string east { get; set; }
        public string west { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
